### ISSUE TITLE
GHP and ipv6 no-go again

### ISSUE THREAD

**Issue by avengerx** [toreanderson/toreanderson.github.io#1]
around 6 years ago, you blogged about an issue: https://github.com/toreanderson/toreanderson.github.io/blob/master/_posts/2015-09-07-working-around-github-pages-and-fastlys-missing-ipv6-support-using-apache-mod_proxy.markdown

two years later, that it was solved: https://github.com/toreanderson/toreanderson.github.io/blob/master/_posts/2017-07-30-update-ghp-fastly-ipv6.markdown

But it seems github went back (maybe in [the 2018 catastrophe](https://github.blog/2018-10-30-oct21-post-incident-analysis/)?) and still to this day, no ipv6 support anywhere about github, including the somewhat-fresh github actions.

**Comment by toreanderson** [comment]
Yeah, I know. Don't have time or energy to hack around it with a proxy at the moment though. Hopefully GitHub fixes it eventually.

**Comment by toreanderson** [comment]
Now fixed, see https://github.blog/changelog/2021-09-30-enabling-ipv6-support-for-github-pages/
